name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Set up Python (match your local version if needed)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      # 3. Install TA-Lib C library from source, then run ldconfig
      - name: Install TA-Lib system library (from source)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzvf ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          ./configure --prefix=/usr
          make
          sudo make install
          sudo ldconfig  # <-- This updates the library cache so -lta-lib is found

      # 4. Install Python dependencies (including `ta-lib`)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Run your tests
      - name: Run tests
        run: |
          pytest
