name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1) Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'

      # 3) Install system prerequisites via Homebrew on macOS
      - name: Install system prerequisites
        run: |
          brew update
          brew install wget postgresql ta-lib autoconf automake libtool

      # 4) Upgrade pip, setuptools, wheel
      - name: Upgrade pip, setuptools, wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      # 5) Install *pinned* NumPy + ta-lib first, then the rest
      - name: Install dependencies
        run: |
          # --- critical pin for TA-Lib compile ---
          python -m pip install "numpy<2.0" "ta-lib==0.4.28"
          # ---------------------------------------
          pip install -r requirements.txt
          pip install pytest

      # 6) Run tests
      - name: Run tests
        run: |
          python -m pytest
