name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1) Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'

      # 3) Install system prerequisites via Homebrew on macOS
      - name: Install system prerequisites
        run: |
          brew update
          brew install wget postgresql ta-lib autoconf automake libtool
          # 'ta-lib' is now installed via Homebrew, so the Python package can find the library.
          # The PostgreSQL installation provides pg_config for psycopg2.

      # 4) Upgrade pip, setuptools, wheel
      - name: Upgrade pip, setuptools, wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      # 5) Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 6) Run tests
      - name: Run tests
        run: |
          pytest
