name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      - name: Install TA-Lib system library (from source)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzvf ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          ./configure --prefix=/usr
          make
          sudo make install
          sudo ldconfig    # important for the ta-lib C library

      # 1) Upgrade pip, setuptools, wheel to ensure the "build_meta" backend is available
      - name: Upgrade build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      # 2) Now install your Python requirements (including ta-lib)
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
