name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1) Check out the repo
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3) Install system packages (TA-Lib C lib + PostgreSQL client)
      - name: Install system dependencies
        run: |
          brew update
          brew install postgresql ta-lib

      # 4) Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt                       # pinned packages
          pip install -e .[test] || true                        # optional: extras defined in pyproject

      # 5) Run test suite
      - name: Run tests
        run: python -m pytest
