name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # 1) Get Python 3.11 from GitHub's toolcache (includes headers)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'

      # 2) Install a compiler toolchain (build-essential) so we can compile C/C++ code
      - name: Install system prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget

      # 3) (Optional) Build and install TA-Lib from source
      - name: Install TA-Lib system library (from source)
        run: |
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzvf ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          ./configure --prefix=/usr
          make
          sudo make install
          sudo ldconfig

      # 4) Upgrade pip, setuptools, wheel
      - name: Upgrade pip, setuptools, wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      # 5) Install your Python dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 6) Run tests
      - name: Run tests
        run: |
          pytest
