name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1) Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Set up Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'

      # 3) Install system prerequisites via Homebrew on macOS
      - name: Install system prerequisites
        run: |
          brew update
          brew install wget postgresql autoconf automake libtool
          # Note: 'build-essential' is an apt-get package on Linux; 
          # on macOS, the GitHub runner already has Xcode command-line tools.

      # 4) (Optional) Build and install TA-Lib from source on macOS
      - name: Install TA-Lib system library (from source)
        run: |
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzvf ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          ./configure --prefix=/usr/local
          make
          sudo make install
          # 'ldconfig' doesn't exist on macOS; you can omit it.

      # 5) Upgrade pip, setuptools, wheel
      - name: Upgrade pip, setuptools, wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      # 6) Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 7) Run tests
      - name: Run tests
        run: |
          pytest
